---
- hosts: all
  become: yes
  tasks:
          - name: install vsftpd
            yum:
              name: vsftpd
              state: installed
            tags: [never, apache]

          - name: install httpd
            yum:
              name: httpd
              state: installed
            tags: [never, beta]
...
