---
- hosts: all
  become: yes
  tasks:
          - name: install vsftpd
            yum:
              name: vsftpd
              state: installed

          - name: install httpd
            yum:
              name: httpd
              state: installed
...
