---
- hosts: all
  tasks:
          - name: install samba
            yum:
              name: samba
              state: installed
          

          - name: install samba
            yum:
              name: smb
              state: installed
            

...
