---
- hosts: all
  become: yes
  tasks:
          - name: install samba
            yum:
              name: samba
              state: installed
      
            

          - name: install httpd
            yum:
              name: httpd
              state: installed
    
            

...
